### PR TITLE
Improve API and expand testing of parse module. Use the new API instead of ParserDB.

### LINKED ISSUE #65: Get rid of parser_db
Rework the optimizations and other features of parser_db into the regular parser library, as they are useful beyond testing.

### PR DESCRIPTION
**Pull request by Renelvon**
### Parse:
- Add `quiet_parse` functionality.
### Parse test:
- Test `quiet_parse`.
- Separate tests of `Parser` class and `parse` module.
- Test `Parser.__init__`.
- Add trivial `pattern` test.
- Use `quiet_parse` instead of `ParserDB`.
- Fix `flake8` warnings. Groom code.
### AST test:
- Use `quiet_parse` instead of `ParserDB`.
- Fix `flake8` warning.
### Type test:
- Use `quiet_parse` instead of `ParserDB`.
### misc:
- Drop `ParserDB`. Fix #65.

### CODE REVIEW

**Comment by dionyziz** [comment]
Aren't we losing memoization optimizations with this?

**Comment by Renelvon** [comment]
Not really. The parsers themselves are no more persistent but the parsing tables still are; they are stored in the temporary `aux_*.py` files, which are kept until a `make cleanaux` is issued. The cost of creating a new parser with pre-built parsing tables is very small, so the testsuite still runs pretty fast. The slowdown is barely noticeable in my laptop.

Also, not reusing old parsers means the tests are a bit closer to being true unit tests.

**Comment by dionyziz** [comment]
So why did we need the memoization previously?

**Comment by Renelvon** [comment]
Flashback: Parser memoization was introduced in #26, for speed, and `ParserDB` was introduced in #54, for factoring the memoization out of the tests.

Before #54, we were creating and caching parsers (as objects). The parsing tables were created as part of the parser initialization but weren't stored by themselves. By reusing the parser (via `self.parsers`), we also resued the parsing tables, so there was speedup.

In order to improve the speed of parser testsuite even more, it was necessary to build the auxiliary parsers with `optimize=True`. This caused PLY to explicitly cache the parsing tables in a file. In #54, the `ParserDB` class was introduced in order to manage the naming of all these auxiliary files and to factor the memoization out of the parser tests, so that it could be used elsewhere too. However, such was the design of `ParserDB` that we ended up caching both the tables (as `aux_*.py` files) as well as the parsers (as objects).

This PR addresses the redundancy as follows: First, the parser initialization code is moved from `ParserDB` to the `parse` module (as suggested here: https://github.com/dionyziz/llama/pull/54/files#r15379019). Second, we forego caching any parser object whatsoever. When a parser is requested whose tables are not already built, PLY builds and saves the tables in a file (as is the case since #54), then a `Parser` object is created. When another parser of the same kind is requested, PLY creates a new parser object but reuses the tables. So, you both get the benefit of a fresh parser as well as the speedup from not recreating the tables. The cost for creating a new parser is completely negligible vis a vis the cost of recreating the parsing tables.

Is it clear now?

**Comment by dionyziz** [comment]
Yup.

**Pull request merged**
